development:
  FOG_MEDIA_DIRECTORY: freelancegrants
  AWS_ACCESS_KEY_ID: AKIAJBF5JZR3I2HCEGUA
  AWS_SECRET_ACCESS_KEY: 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
production:
  FOG_MEDIA_DIRECTORY: freelancegrants
  AWS_ACCESS_KEY_ID: AKIAJBF5JZR3I2HCEGUA
  AWS_SECRET_ACCESS_KEY: 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

#for heroku
#export AWS_ACCESS_KEY_ID="AKIAJBF5JZR3I2HCEGUA"
